### ISSUE TITLE
Facing error: Error using load_nii_hdr (line 39)

### ISSUE THREAD

**Issue by pradhanhitesh** [volBrain/AssemblyNet#11]
Hello developers! I am currently facing issue when run any T1.nii image in the following form:

THE ERROR:
**num t1_filenames= 1
./volBrain_v10_preprocessing_exe.sh /tmp/t1_0 /tmp
Error using load_nii_hdr (line 39)
Cannot find file "/tmp/t1_0.hdr".
Error in load_untouch_nii (line 154)
Error in read_nifti (line 9)
Error in sv_segment_preprocessing (line 88)**

Can anyone please share their views/comments on how to resolve the issue? I am running on Ubuntu 20.04.6 with 200 GB RAM and 48 GB Threadripper Pro.

**Comment by BorisMansencal** [comment]
Hi @pradhanhitesh 

Could you share a nifti file that produces this error?

Thanks.

**Comment by pradhanhitesh** [comment]
Thank you for you response. 

How do you suggest I share the nifti file?

**Comment by BorisMansencal** [comment]
You could use google drive or dropbox for example.

**Comment by pradhanhitesh** [comment]
Here is the link. I will approve the access once requested. Also, I checked with multiple .nii files from our study, it did not work. 

Google Drive: https://drive.google.com/drive/folders/12e7KpWkamozTbYv1Gegs5Hz53c3cUYW4?usp=sharing

**Comment by BorisMansencal** [comment]
I have sent a request.

I did not think about it, but you could also have submitted a job on [volbrain.net](https://volbrain.net/) with the AssemblyNet pipeline and tell us the job id.

**Comment by pradhanhitesh** [comment]
I have not used AssemblyNet on volbrain yet. I will look into it and let you know. However, I was hoping if I could run AssemblyNet on local system. But before I could do that, I encountered the error here. 

PS: I just approved the Google Drive request.

**Comment by BorisMansencal** [comment]
I tried your image and it works fine on our machines.
You could try to process this exemple image https://github.com/volBrain/AssemblyNet/blob/main/example/my_brain.nii.gz

If this doesn't work, your configuration is probably not compatible with our docker image. We do not have access to any Threadripper Pro processor for testing.
You can try on another machine or use the volbrain.net platform...

**Comment by hippocampo** [comment]
Hello!  Wanted to report that I am finding the same problem as pradhanhitesh and wondering if anyone has insight into the problem.  I'm running Ubuntu 22.0.4 with a 12Gb RTX 3060.  The example image did not work for me either, unfortunately.
Due to clinical data privacy issues I am not able to use the volbrain.net platform.
Also, the output command throws an error if I specify a specific file (e.g. /data/image.nii.gz) rather than a folder (e.g. /data/)?
Many thanks to all the developers for your amazing work on this software.

**Comment by BorisMansencal** [comment]
Could you try processing this image https://github.com/volBrain/AssemblyNet/blob/main/example/my_brain.nii.gz on your local machine? Does it work?
If not, could you provide the versions of Docker and of the nvidia driver you are using?

Thanks.

**Comment by hippocampo** [comment]
Ah okay so I figured it out.  This always happens after I post something!
The problem was that I had been binding the docker to an image, rather than a folder.  So for example:
WRONG: docker run --rm -v /path/to/T1-image.nii.gz:/data volbrain/assemblynet:1.0.0 /data/
RIGHT: docker run --rm -v /path/to/FOLDER_WITH_T1_image:/data volbrain/assemblynet:1.0.0 /data/your_T1_image.nii.gz

Hope this helps for anyone else getting this error.  Thank you @BorisMansencal for the help!

**Comment by pradhanhitesh** [comment]
@hippocampo Thanks for the solution! It did work but with a slightly different input than yours. 

As suggested by you I tried:
**docker run --rm -v /path/to/FOLDER_WITH_T1_image:/data volbrain/assemblynet:1.0.0 /data/your_T1_image.nii.gz**
But it threw a filename or directory error.

So, I looked up the args in volBrain GitHub page and modified my input as:
**docker run --rm -v /path/to/FOLDER_WITH_T1_image:/data -v /path/to/FOLDER_WITH_T1_image:/data_out volbrain/assemblynet:1.0.0 /data /data_out**
And the process is currently running as I am writing this.

**Comment by BorisMansencal** [comment]
@pradhanhitesh your first command should work.
You could check that your image file is seen by docker, by launching docker in interactive mode:
`docker run --rm -it --entrypoint /bin/bash -v /path/to/FOLDER_WITH_T1_image:/data volbrain/assemblynet:1.0.0 `
and then doing:
`ls /data`
If your image is not listed, the docker bind mount did not work correctly.
Maybe it is related to your path name or image name...

**Comment by pradhanhitesh** [comment]
Thank you @BorisMansencal ! I could not get back to you earlier. 

Due to my silly mistake, the first command did not work the way it is supposed to work. I rectified the error and now it is working like a charm.

**Comment by BorisMansencal** [comment]
Ok, perfect.
I close this issue.
